---
default_host_ip: ""

pods:
  - name: socks5-proxy
    image: serjs/go-socks5-proxy:master
    state: started
    restart: unless-stopped
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    ports:
      - 1080:1080
