---
standard_pod_path_prefix: "/opt/pods"

pods:
  - name: socks5-proxy
    image: serjs/go-socks5-proxy:master
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    ports: ["1080:1080"]

  - name: meshmon
    image: ghcr.io/ripplefcl/meshmon:v3.0.1
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    ports: ["8000:8000"]
    volumes: ["{{ standard_pod_path_prefix }}/meshmon/config:/app/config"]
