---
user_pods:
  - name: cyberchef
    image: ghcr.io/gchq/cyberchef:10.19.4
    publish:
      - "8080:80"

  - name: it-tools
    image: docker.io/corentinth/it-tools:latest
    publish:
      - "8081:80"

  - name: networking-toolbox
    image: ghcr.io/lissy93/networking-toolbox:1.5.0
    publish:
      - "8082:3000"

  - name: omni-tools
    image: docker.io/iib0011/omni-tools:0.6.0
    publish:
      - "8083:80"
