---
standard_pod_path_prefix: "/tank/pods"
storage_pod_path_prefix: "/tank/pods"

pods:
  - name: scrutiny-collector
    image: ghcr.io/analogj/scrutiny:v0.8.1-collector
    capabilities:
      - SYS_ADMIN
      - SYS_RAWIO
    env:
      COLLECTOR_API_ENDPOINT: "{{ lookup('ripplefcl.bwscache.secret', 'scrutiny_domain').value }}"
      COLLECTOR_HOST_ID: "{{ inventory_hostname }}"
      COLLECTOR_CRON_SCHEDULE: "0 * * * *"
      COLLECTOR_RUN_STARTUP: "true"
    volumes:
      - "/run/udev:/run/udev:ro"
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd

  - name: bw-backup
    image: docker.io/reaper0x1/bitwarden-portal:1.0.2
    env:
      PUID: "{{ ansible_facts.user_uid | string }}"
      PGID: "{{ ansible_facts.user_gid | string }}"
      CRON_SCHEDULE: "0 0 * * *"
      ENCRYPTION_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'bwb_encryption').value }}"
      SOURCE_ACCOUNT: "{{ lookup('ripplefcl.bwscache.secret', 'will_email').value }}"
      SOURCE_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'bw_pass').value }}"
      SOURCE_CLIENTID: "{{ lookup('ripplefcl.bwscache.secret', 'bw_clientid').value }}"
      SOURCE_CLIENT_SECRET: "{{ lookup('ripplefcl.bwscache.secret', 'bw_clientsecret').value }}"
      SOURCE_SERVER: "https://vault.bitwarden.com"
      DEST_ACCOUNT: "{{ lookup('ripplefcl.bwscache.secret', 'will_email').value }}"
      DEST_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'vw_pass').value }}"
      DEST_CLIENTID: "{{ lookup('ripplefcl.bwscache.secret', 'vw_clientid').value }}"
      DEST_CLIENT_SECRET: "{{ lookup('ripplefcl.bwscache.secret', 'vw_clientsecret').value }}"
      DEST_SERVER: "{{ lookup('ripplefcl.bwscache.secret', 'vw_domain').value }}"
      ENABLE_PRUNING: "true"
      RETENTION_DAYS: "30"
      MIN_FILES: "10"
    volumes:
      - "/tank/backups/bitwarden:/app/backups"

  - name: garage
    image: docker.io/dxflrs/garage:v2.0.0
    network_mode: host
    volumes:
      - "/tank/pods/garage/config/garage.toml:/etc/garage.toml"
      - "/tank/pods/garage/meta:/var/lib/garage/meta"
      - "/tank/pods/garage/data:/var/lib/garage/data"
