---
standard_pod_path_prefix: "/tank/pods"
storage_pod_path_prefix: "/tank/pods"

pods:
  - name: scrutiny-collector
    image: ghcr.io/analogj/scrutiny:v0.8.1-collector
    capabilities:
      - SYS_ADMIN
      - SYS_RAWIO
    env:
      COLLECTOR_API_ENDPOINT: "{{ lookup('ripplefcl.bwscache.secret', 'scrutiny_domain').value }}"
      COLLECTOR_HOST_ID: "{{ inventory_hostname }}"
      COLLECTOR_CRON_SCHEDULE: "0 * * * *"
      COLLECTOR_RUN_STARTUP: "true"
    volumes: ["/run/udev:/run/udev:ro"]
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
    state: absent

  - name: garage
    image: docker.io/dxflrs/garage:v2.1.0
    network_mode: host
    volumes:
      - "/tank/pods/garage/config/garage.toml:/etc/garage.toml"
      - "/tank/pods/garage/meta:/var/lib/garage/meta"
      - "/tank/pods/garage/data:/var/lib/garage/data"
