---
default_host_ip: ""

pods:
  - name: scrutiny-collector
    image: ghcr.io/analogj/scrutiny:v0.8.1-collector
    restart: unless-stopped
    state: started
    capabilities:
      - SYS_ADMIN
      - SYS_RAWIO
    env:
      COLLECTOR_API_ENDPOINT: "{{ lookup('ripplefcl.bwscache.secret', 'domain_scrutiny').value }}"
      COLLECTOR_HOST_ID: "{{ ansible_hostname }}"
      COLLECTOR_CRON_SCHEDULE: "0 * * * *"
      COLLECTOR_RUN_STARTUP: "true"
    volumes:
      - "/run/udev:/run/udev:ro"
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd

  - name: netboot
    image: ghcr.io/netbootxyz/netbootxyz:0.7.6-nbxyz4
    restart: unless-stopped
    state: started
    ports:
      - 3000:3000
      - 69:69/udp
      - 8900:80
    volumes:
      - "/tank/pods/netbootxyz/config:/config"
      - "/tank/pods/netbootxyz/assets:/assets"

  - name: files
    image: public.ecr.aws/nginx/nginx:1.29.0
    restart: unless-stopped
    state: started
    ports:
      - 8084:80
    env:
      NGINX_HOST: "files.int.mcda.dev"
      NGINX_PORT: "80"
    volumes:
      - "/tank/virt/iso:/var/www"
      - "/tank/pods/nginx/nginx.conf:/etc/nginx/nginx.conf"

  - name: bw-backup
    image: docker.io/reaper0x1/bitwarden-portal:1.0.2
    restart: unless-stopped
    state: started
    env:
      PUID: "{{ ansible_facts.user_uid }}"
      PGID: "{{ ansible_facts.user_gid }}"
      TZ: "Europe/London"
      CRON_SCHEDULE: "0 0 * * *"
      ENCRYPTION_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'bwb_encryption').value }}"
      SOURCE_ACCOUNT: "{{ lookup('ripplefcl.bwscache.secret', 'will_email').value }}"
      SOURCE_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'bw_pass').value }}"
      SOURCE_CLIENTID: "{{ lookup('ripplefcl.bwscache.secret', 'bw_clientid').value }}"
      SOURCE_CLIENT_SECRET: "{{ lookup('ripplefcl.bwscache.secret', 'bw_clientsecret').value }}"
      SOURCE_SERVER: "https://vault.bitwarden.com"
      DEST_ACCOUNT: "{{ lookup('ripplefcl.bwscache.secret', 'will_email').value }}"
      DEST_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'vw_pass').value }}"
      DEST_CLIENTID: "{{ lookup('ripplefcl.bwscache.secret', 'vw_clientid').value }}"
      DEST_CLIENT_SECRET: "{{ lookup('ripplefcl.bwscache.secret', 'vw_clientsecret').value }}"
      DEST_SERVER: "{{ lookup('ripplefcl.bwscache.secret', 'vw_domain').value }}"
      ENABLE_PRUNING: "true"
      RETENTION_DAYS: "30"
      MIN_FILES: "10"
    volumes:
      - "/tank/backups/bitwarden:/app/backups"
