---
default_host_ip: ""

pods:
  - name: scrutiny-collector
    image: ghcr.io/analogj/scrutiny:v0.8.1-collector
    restart: unless-stopped
    state: started
    capabilities:
      - SYS_ADMIN
      - SYS_RAWIO
    env:
      COLLECTOR_API_ENDPOINT: "{{ lookup('ripplefcl.bwscache.secret', 'domain_scrutiny').value }}"
      COLLECTOR_HOST_ID: "{{ ansible_hostname }}"
      COLLECTOR_CRON_SCHEDULE: "0 * * * *"
      COLLECTOR_RUN_STARTUP: "true"
    volumes:
      - "/run/udev:/run/udev:ro"
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd

  - name: netboot
    image: ghcr.io/netbootxyz/netbootxyz:0.7.6-nbxyz4
    restart: unless-stopped
    state: started
    ports:
      - 3000:3000
      - 69:69/udp
      - 8900:80
    volumes:
      - "/tank/pods/netbootxyz/config:/config"
      - "/tank/pods/netbootxyz/assets:/assets"

  - name: files
    image: public.ecr.aws/nginx/nginx:1.27.4
    restart: unless-stopped
    state: started
    ports:
      - 8084:80
    env:
      NGINX_HOST: "files.int.mcda.dev"
      NGINX_PORT: "80"
    volumes:
      - "/tank/virt/iso:/var/www"
      - "/tank/pods/nginx/nginx.conf:/etc/nginx/nginx.conf"
