---
- name: Gather facts about libvirt network
  community.libvirt.virt_net:
    command: facts

- name: Gather facts about libvirt storage pools
  community.libvirt.virt_pool:
    command: facts

- name: Install apt packages
  ansible.builtin.include_tasks: install.yml

- name: Configure libvirt
  ansible.builtin.include_tasks: standard.yml

- name: Start libvirt services
  ansible.builtin.include_tasks: services.yml

- name: Configure libvirt network
  ansible.builtin.include_tasks: network.yml
  loop: "{{ deb_libvirt_net_nics }}"
  loop_control:
    label: "{{ item.name }}"

- name: Configure libvirt storage
  ansible.builtin.include_tasks: storage.yml
  loop: "{{ deb_libvirt_storage_pools }}"
  loop_control:
    label: "{{ item.name }}"
