---
- name: Install remi repo
  ansible.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-9.rpm
    disable_gpg_check: true
    state: present

- name: Refresh cache
  ansible.builtin.dnf:
    update_cache: true

- name: Install Apache, PHP, and MariaDB
  ansible.builtin.dnf:
    name:
      - "@php:remi-8.0"
      - php-cli
      - php-fpm
      - php-gd
      - php-intl
      - php-mbstring
      - php-mysqlnd
      - php-opcache
      - php-pdo
      - php-pecl-zip
      - php-sodium
      - php-xml
      - httpd
      - mod_ssl
      - mariadb-server
    state: present

- name: Create user John
  ansible.builtin.user:
    name: john
    create_home: true
    shell: /bin/bash
    password: '{{ john_password }}'
    state: present
    groups: apache
    append: true
  no_log: true
