---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "node-exporter"
    scheme: http
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/node-exporter/*.json
        refresh_interval: 5s

  - job_name: "traefik"
    scheme: https
    metrics_path: "/metrics"
    static_configs:
      - targets: ["traefik.int.mcda.dev"]
        labels:
          env: int
      - targets: ["traefik.ext.mcda.dev"]
        labels:
          env: ext

  - job_name: "gravity"
    static_configs:
      - targets:
          - 10.10.0.3:8009

  - job_name: "nut-exporter"
    metrics_path: "/ups_metrics"
    scheme: http
    static_configs:
      - targets: ["sbc1:9199"]
        labels:
          ups: "primary"
    params:
      ups: ["will-office-eaton"]

  - job_name: "unpoller"
    scheme: http
    static_configs:
      - targets: ["sbc3:9130"]

  - job_name: "mktxp"
    static_configs:
      - targets: ["mktxp:49090"]
