---
collections:
  - name: ansible.utils
    version: 5.1.2
  - name: community.docker
    version: 4.3.1
  - name: community.general
    version: 10.3.0
  - name: community.sops
    version: 2.0.1
  - name: prometheus.prometheus
    version: 0.24.1

roles:
  - name: geerlingguy.docker
    version: 7.4.4
  - name: geerlingguy.git
    version: 3.0.1
  - name: geerlingguy.pip
    version: 3.1.0
