---
collections:
  - name: ansible.utils
  - name: community.general
  - name: community.docker
  - name: community.sops
  - name: prometheus.prometheus
  - name: netbox.netbox
  - name: napalm.napalm

roles:
  - name: geerlingguy.docker
  - name: geerlingguy.git
  - name: geerlingguy.pip
  - name: artis3n.tailscale
