---
default_host_ip: ""

pods:
  - name: mc-router
    image: ghcr.io/itzg/mc-router:1.34.2
    restart: unless-stopped
    state: started
    networks:
      - name: minecraft
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    env:
      MAPPING: |
        ftb.int.mcda.dev=ftb-neotech:25565
    ports:
      - 25565:25565

  - name: ftb-neotech
    image: ghcr.io/itzg/minecraft-server:2025.8.1-java17
    restart: unless-stopped
    state: started
    networks:
      - name: minecraft
    tty: true
    interactive: true
    env:
      UID: "{{ ansible_facts.user_uid }}"
      GID: "{{ ansible_facts.user_gid }}"
      TZ: "Europe/London"
      MEMORY: "8G"
      USE_MEOWICE_FLAGS: "true"
      EULA: "true"
      TYPE: "FTBA"
      CF_API_KEY: "{{ lookup('ripplefcl.bwscache.secret', 'curseforge_token').value }}"
      FTB_MODPACK_ID: "123"
      FTB_MODPACK_VERSION_ID: "100100"
    volumes:
      - "/opt/pods/minecraft/ftb-neotech/data:/data"

pod_networks:
  - name: minecraft
    driver: local
