---
default_host_ip: ""

pods:
  - name: traefik
    image: public.ecr.aws/docker/library/traefik:3.5.0
    restart: always
    state: started
    security_opt:
      - "no-new-privileges:true"
    network_mode: host
    env:
      BUNNY_API_KEY: "{{ lookup('ripplefcl.bwscache.secret', 'bunny_api').value }}"
      BUNNY_POLLING_TIMEOUT: "600"
      BUNNY_POLLING_INTERVAL: "5"
      BUNNY_TTL: "3600"
      CF_API_EMAIL: "{{ lookup('ripplefcl.bwscache.secret', 'will_email').value }}"
      CF_API_KEY: "{{ lookup('ripplefcl.bwscache.secret', 'cf_token').value }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "~/pods/traefik/config/traefik.yml:/traefik.yml:ro"
      - "~/pods/traefik/config/providers:/providers:ro"
      - "~/pods/traefik/config/acme.json:/acme.json"

  - name: immich-public-proxy
    image: ghcr.io/alangrainger/immich-public-proxy:1.13.0
    restart: unless-stopped
    state: started
    network_mode: host
    env:
      IMMICH_URL: "http://[fd72:1432:d17a:0:be24:11ff:fe8a:aa24]:2283"

  - name: ping-api
    image: ghcr.io/vellfire/ping-api:1.1.0
    restart: unless-stopped
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    network_mode: host
    env:
      PORT: "8912"
      ENDPOINT: "172.16.110.2"

  - name: mariadb_ts6
    image: public.ecr.aws/docker/library/mariadb:11.8.2
    restart: unless-stopped
    state: started
    networks:
      - name: ts6
    env:
      MARIADB_ROOT_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'ts6_db_root').value }}"
      MARIADB_USER: "ts6-user"
      MARIADB_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'ts6_db_user').value }}"
      MARIADB_DATABASE: "ts6-db"
    volumes:
      - "/opt/pods/mariadb_ts6/data:/var/lib/mysql"
      - "/opt/pods/mariadb_ts6/backup:/backup"

  - name: ts6-server
    image: docker.io/teamspeaksystems/teamspeak6-server:v6.0.0-beta5
    restart: unless-stopped
    state: started
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    networks:
      - name: ts6
    ports:
      - "9987:9987/udp"
      - "30033:30033/tcp"
    env:
      TSSERVER_LICENSE_ACCEPTED: "accept"
      TSSERVER_DATABASE_PLUGIN: "mariadb"
      TSSERVER_DATABASE_HOST: "mariadb_ts6"
      TSSERVER_DATABASE_PORT: "3306"
      TSSERVER_DATABASE_NAME: "ts6-db"
      TSSERVER_DATABASE_USERNAME: "ts6-user"
      TSSERVER_DATABASE_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'ts6_db_user').value }}"
      TSSERVER_DATABASE_SQL_CREATE_PATH: create_mariadb
    volumes:
      - "/opt/pods/ts6-server:/var/tsserver"

pod_networks:
  - name: proxy
    driver: local
  - name: ts6
    driver: local
