---
default_host_ip: ""

pods:
  - name: traefik
    image: public.ecr.aws/docker/library/traefik:3.4.1
    restart: always
    state: started
    security_opt:
      - "no-new-privileges:true"
    network_mode: host
    env:
      BUNNY_API_KEY: "{{ lookup('ripplefcl.bwscache.secret', 'api_bunny').value }}"
      BUNNY_POLLING_TIMEOUT: "600"
      BUNNY_POLLING_INTERVAL: "5"
      BUNNY_TTL: "3600"
      CF_API_EMAIL: "{{ lookup('ripplefcl.bwscache.secret', 'api_cf_user').value }}"
      CF_API_KEY: "{{ lookup('ripplefcl.bwscache.secret', 'api_cf_token').value }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "~/pods/traefik/config/traefik.yml:/traefik.yml:ro"
      - "~/pods/traefik/config/providers:/providers:ro"
      - "~/pods/traefik/config/acme.json:/acme.json"

  - name: immich-public-proxy
    image: ghcr.io/alangrainger/immich-public-proxy:1.11.3
    restart: unless-stopped
    state: started
    network_mode: host
    env:
      IMMICH_URL: "http://[fd72:1432:d17a:0:be24:11ff:fe8a:aa24]:2283"

  - name: ping-api
    image: ghcr.io/vellfire/ping-api:1.0.1
    restart: unless-stopped
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    network_mode: host
    env:
      PORT: "8912"
      ENDPOINT: "172.16.110.2"

pod_networks:
  - name: proxy
    driver: local
