---
linux:
  children:
    debian:
      hosts:
        smi-do-01:
          ansible_host: smi-do-01.virt.lan
        smi-ui-01:
          ansible_host: smi-ui-01.mgt.lan

    rhel:
      children:
        rocky:
          hosts:
            amstamps-web:
              ansible_host: amstamps-web.virt.lan
            bntva-web:
              ansible_host: bntva-web.virt.lan
            smi-do-02:
              ansible_host: smi-do-02.virt.lan
            smi-db-01:
              ansible_host: smi-db-01.virt.lan
            # smi-rl-01:
              # ansible_host: smi-rl-01.mgt.lan
            smi-rl-02:
              ansible_host: smi-rl-02.mgt.lan
            smi-rl-03:
              ansible_host: smi-rl-03.mgt.lan
            smi-rl-04:
              ansible_host: smi-rl-04.mgt.lan
            smi-rl-05:
              ansible_host: smi-rl-05.mgt.lan
            ovh-rl-01:
              ansible_host: ovh-rl-01.ovh.lan
            ovh-rl-02:
              ansible_host: ovh-rl-02.ovh.lan
            ovh-rl-03:
              ansible_host: ovh-rl-03.ovh.lan

    docker:
      hosts:
        # smi-rl-01:
          # ansible_host: smi-rl-01.mgt.lan
        smi-rl-02:
          ansible_host: smi-rl-02.mgt.lan
        smi-rl-03:
          ansible_host: smi-rl-03.mgt.lan
        smi-rl-04:
          ansible_host: smi-rl-04.mgt.lan
        smi-rl-05:
          ansible_host: smi-rl-05.mgt.lan
        smi-do-01:
          ansible_host: smi-do-01.virt.lan
        smi-do-02:
          ansible_host: smi-do-02.virt.lan
        smi-db-01:
          ansible_host: smi-db-01.virt.lan
        smi-ui-01:
          ansible_host: smi-ui-01.mgt.lan
        ovh-rl-01:
          ansible_host: ovh-rl-01.ovh.lan
        ovh-rl-02:
          ansible_host: ovh-rl-02.ovh.lan
        ovh-rl-03:
          ansible_host: ovh-rl-03.ovh.lan

    virt:
      hosts:
        # smi-rl-01:
          # ansible_host: smi-rl-01.mgt.lan
        smi-rl-02:
          ansible_host: smi-rl-02.mgt.lan
        smi-rl-03:
          ansible_host: smi-rl-03.mgt.lan
        smi-rl-04:
          ansible_host: smi-rl-04.mgt.lan

    ovh:
      hosts:
        ovh-rl-01:
          ansible_host: ovh-rl-01.ovh.lan
        ovh-rl-02:
          ansible_host: ovh-rl-02.ovh.lan
        ovh-rl-03:
          ansible_host: ovh-rl-03.ovh.lan


switches:
  children:
    juniper:
      hosts:
        smi-sw-02:
          ansible_host: 10.141.1.202
        smi-sw-03:
          ansible_host: 10.141.1.203
