---
unix:
  children:
    macbook:
      hosts:
        Will-MBP:
          ansible_host: localhost
          ansible_connection: local

    linux:
      children:
        rhel:
          children:
            rocky:
              hosts:
                smi-rl-01:
                  ansible_host: smi-rl-01
                smi-rl-02:
                  ansible_host: smi-rl-02
                smi-rl-03:
                  ansible_host: smi-rl-03
                smi-rl-04:
                  ansible_host: smi-rl-04
                ovh-rl-01:
                  ansible_host: ovh-rl-01
                ovh-rl-02:
                  ansible_host: ovh-rl-02
                ovh-rl-03:
                  ansible_host: ovh-rl-03

        docker:
          hosts:
            smi-rl-01:
              ansible_host: smi-rl-01
            smi-rl-02:
              ansible_host: smi-rl-02
            smi-rl-03:
              ansible_host: smi-rl-03
            smi-rl-04:
              ansible_host: smi-rl-04

        virt:
          hosts:
            smi-rl-01:
              ansible_host: smi-rl-01
            smi-rl-02:
              ansible_host: smi-rl-02
            smi-rl-03:
              ansible_host: smi-rl-03
            smi-rl-04:
              ansible_host: smi-rl-04

        web:
          hosts:
            ovh-rl-02:
              ansible_host: ovh-rl-02
            ovh-rl-03:
              ansible_host: ovh-rl-03

        media:
          hosts:
            smi-rl-03:

home:
  hosts:
    smi-rl-01:
      ansible_host: smi-rl-01
    smi-rl-02:
      ansible_host: smi-rl-02
    smi-rl-03:
      ansible_host: smi-rl-03
    smi-rl-04:
      ansible_host: smi-rl-04

ovh:
  hosts:
    ovh-rl-01:
      ansible_host: ovh-rl-01
    ovh-rl-02:
      ansible_host: ovh-rl-02
    ovh-rl-03:
      ansible_host: ovh-rl-03

switches:
  children:
    juniper:
      hosts:
        smi-sw-02:
          ansible_host: 10.141.1.202
        smi-sw-03:
          ansible_host: 10.141.1.203
