---
unix:
  children:
    macbook:
      hosts:
        Will-MBP:
          ansible_host: localhost
          ansible_connection: local

    linux:
      children:
        rhel:
          children:
            rocky:
              hosts:
                smi-rl-01:
                  ansible_host: smi-rl-01.mgt.lan
                smi-rl-05:
                  ansible_host: smi-rl-05.mgt.lan
                smi-pi-01:
                  ansible_host: smi-pi-01.mgt.lan
                smi-dt-01:
                  ansible_host: smi-dt-01.mgt.lan
                ovh-rl-01:
                  ansible_host: 172.16.0.0
                ovh-rl-02:
                  ansible_host: 172.16.0.2
                ovh-rl-03:
                  ansible_host: 172.16.0.3

        docker:
          hosts:
            smi-rl-01:
            smi-pi-01:
            smi-rl-05:
            smi-dt-01:

        virt:
          hosts:
            smi-rl-01:
            smi-rl-05:
            smi-dt-01:

        web:
          hosts:
            ovh-rl-02:
            ovh-rl-03:

        media:
          hosts:
            smi-rl-01:

home:
  hosts:
    smi-rl-01:
    smi-rl-05:
    smi-pi-01:
    smi-dt-01:

ovh:
  hosts:
    ovh-rl-01:
    ovh-rl-02:
    ovh-rl-03:
