---
unix:
  children:
    macbook:
      hosts:
        Will-MBP:
          ansible_host: localhost
          ansible_connection: local

    linux:
      children:
        rhel:
          children:
            rocky:
              hosts:
                amstamps-web:
                  ansible_host: amstamps-web.virt.lan
                bntva-web:
                  ansible_host: bntva-web.virt.lan
                # smi-rl-01:
                  # ansible_host: smi-rl-01.mgt.lan
                smi-rl-02:
                  ansible_host: smi-rl-02.mgt.lan
                smi-rl-03:
                  ansible_host: smi-rl-03.mgt.lan
                smi-rl-04:
                  ansible_host: smi-rl-04.mgt.lan
                # smi-rl-05:
                #   ansible_host: smi-rl-05.mgt.lan
                # ovh-rl-01:
                #   ansible_host: ovh-rl-01.ovh.lan
                # ovh-rl-01:
                #   ansible_host:
                # ovh-rl-02:
                #   ansible_host:
                # ovh-rl-03:
                #   ansible_host:

        docker:
          hosts:
            # smi-rl-01:
              # ansible_host: smi-rl-01.mgt.lan
            smi-rl-02:
              ansible_host: smi-rl-02.mgt.lan
            smi-rl-03:
              ansible_host: smi-rl-03.mgt.lan
            smi-rl-04:
              ansible_host: smi-rl-04.mgt.lan
            smi-rl-05:
              ansible_host: smi-rl-05.mgt.lan

        virt:
          hosts:
            # smi-rl-01:
              # ansible_host: smi-rl-01.mgt.lan
            smi-rl-02:
              ansible_host: smi-rl-02.mgt.lan
            smi-rl-03:
              ansible_host: smi-rl-03.mgt.lan
            smi-rl-04:
              ansible_host: smi-rl-04.mgt.lan

        web:
          hosts:
            ovh-rl-02:
              ansible_host: ovh-rl-02
            ovh-rl-03:
              ansible_host: ovh-rl-03

        media:
          hosts:
            smi-rl-03:

switches:
  children:
    juniper:
      hosts:
        smi-sw-02:
          ansible_host: 10.141.1.202
        smi-sw-03:
          ansible_host: 10.141.1.203
