---
linux:
  children:
    debian:
      hosts:
        media.mgt.lan:
        pi3b.mgt.lan:
        do1.virt.lan:
        wifi.mgt.lan:

    
    rhel:
      children:
        rocky:
          hosts:
            amstamps-web.virt.lan:
            bntva-web.virt.lan:
            mcd-wg1:
              ansible_user: ec2-user
            do2.virt.lan:

    docker:
      hosts:
        media.mgt.lan:
        pi3b.mgt.lan:
        do1.virt.lan:
        do2.virt.lan:
        wifi.mgt.lan:
