---
pods:
  - name: mariadb_ams
    image: public.ecr.aws/docker/library/mariadb:10.5.23
    networks: [{ name: db }]
    ports: ["15000:3306"]
    env:
      MARIADB_ROOT_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'dad_db_root').value }}"
    volumes:
      - "/opt/pods/mariadb_ams/data:/var/lib/mysql"
      - "/opt/pods/mariadb_ams/config/my.cnf:/etc/mysql/my.cnf"
      - "/opt/pods/mariadb_ams/config/backup.cnf:/etc/mysql/backup.cnf"
      - "/opt/pods/mariadb_ams/backup:/backup"

  - name: mariadb_bnt
    image: public.ecr.aws/docker/library/mariadb:10.5.23
    networks: [{ name: db }]
    ports: ["15001:3306"]
    env:
      MARIADB_ROOT_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'dad_db_root').value }}"
    volumes:
      - "/opt/pods/mariadb_bnt/data:/var/lib/mysql"
      - "/opt/pods/mariadb_bnt/backup:/backup"

  - name: media-db
    image: public.ecr.aws/docker/library/postgres:17.6
    networks: [{ name: db }]
    ports: ["15002:5432"]
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    env:
      POSTGRES_USER: "media"
      POSTGRES_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'media_db_pass').value }}"
    volumes: ["/opt/pods/media-db/pgdata:/var/lib/postgresql/data"]

  - name: alloy
    image: docker.io/grafana/alloy:v1.11.0
    ports:
      - "12346:12345"
      - "1514:1514/udp"
    command: "run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy"
    volumes:
      - "/opt/pods/alloy/data:/var/lib/alloy/data"
      - "/opt/pods/alloy/config/config.alloy:/etc/alloy/config.alloy"

  - name: db_backup
    image: ghcr.io/tiredofit/docker-db-backup:4.1.21
    networks: [{ name: db }]
    env:
      MODE: "AUTO"
      DEFAULT_BACKUP_LOCATION: "S3"
      DEFAULT_COMPRESSION_LEVEL: "9"
      DEFAULT_BACKUP_INTERVAL: "1440"
      DEFAULT_BACKUP_BEGIN: "0000"
      DEFAULT_CLEANUP_TIME: "10080"
      DEFAULT_MYSQL_CLIENT: "mariadb"
      DEFAULT_S3_BUCKET: "mariadb-bucket"
      DEFAULT_S3_KEY_ID: "{{ lookup('ripplefcl.bwscache.secret', 'mariadb_bucket_key_id').value }}"
      DEFAULT_S3_KEY_SECRET: "{{ lookup('ripplefcl.bwscache.secret', 'mariadb_bucket_key_secret').value }}"
      DEFAULT_S3_REGION: "garage"
      DEFAULT_S3_HOST: "10.10.0.3:3900"
      DEFAULT_S3_PROTOCOL: "http"
      CONTAINER_ENABLE_MONITORING: "false"
      DB01_S3_PATH: "ams"
      DB01_TYPE: "mysql"
      DB01_HOST: "mariadb_ams"
      DB01_NAME: "ALL"
      DB01_USER: "root"
      DB01_PASS: "{{ lookup('ripplefcl.bwscache.secret', 'dad_db_root').value }}"
      DB02_S3_PATH: "bnt"
      DB02_TYPE: "mysql"
      DB02_HOST: "mariadb_bnt"
      DB02_NAME: "ALL"
      DB02_USER: "root"
      DB02_PASS: "{{ lookup('ripplefcl.bwscache.secret', 'dad_db_root').value }}"
      DB03_S3_PATH: "media"
      DB03_TYPE: "pgsql"
      DB03_HOST: "media-db"
      DB03_NAME: "ALL"
      DB03_USER: "media"
      DB03_PASS: "{{ lookup('ripplefcl.bwscache.secret', 'media_db_pass').value }}"

pod_networks:
  - name: db
    driver: local
