---
restic_repos:
  vdb1:
    location: "s3:{{ lookup('ripplefcl.bwscache.secret', 's3_domain').value }}/restic-backup/vdb1"
    init: true
    password: "{{ lookup('ripplefcl.bwscache.secret', 'restic_s3_secret_key').value }}"
    aws_access_key: "{{ lookup('ripplefcl.bwscache.secret', 'restic_s3_access_key').value }}"
    aws_secret_access_key: "{{ lookup('ripplefcl.bwscache.secret', 'restic_s3_secret_key').value }}"
    aws_default_region: us-east-1

restic_backups:
  pods:
    name: pods
    repo: vdb1
    src: /opt/pods
    scheduled: true
    schedule_oncalendar: '*-*-* 04:00:00'
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 6
    keep_yearly: 2
    prune: true
    exclude:
      exclude:
        - "/opt/pods/gravity"
        - "/opt/pods/seaweedfs"
        - "/opt/pods/mariadb_ams"
        - "/opt/pods/mariadb_bnt"
        - "/opt/pods/media-db"
        - "/opt/pods/gitea-db"
        - "/opt/pods/unifi-db"
        - "/opt/pods/seaweedfs-db"
        - "/opt/pods/immich_postgres"
        - "/opt/pods/*/pgdata"
        - "/opt/pods/prometheus/data"
        - "/opt/pods/loki/data"
        - "/opt/pods/*/cache"
        - "/opt/pods/*/tmp"
        - "/opt/seaweedfs"
