---
- name: Setup traefik
  when: item.name == "traefik"
  block:
    - name: Create providers folder
      ansible.builtin.file:
        path: /opt/pods/traefik/providers
        state: directory
        recurse: true
        mode: "0755"

    - name: Create traefik yml
      ansible.builtin.template:
        src: traefik/traefik.yml.j2
        dest: /opt/pods/traefik/traefik.yml
        mode: "0644"

    - name: Create acme.json
      ansible.builtin.file:
        path: /opt/pods/traefik/acme.json
        state: touch
        mode: "0600"

    - name: Create middleware config
      ansible.builtin.template:
        src: traefik/middlewares.yml.j2
        dest: /opt/pods/traefik/providers/middlewares.yml
        mode: "0644"

    - name: Create router config
      ansible.builtin.template:
        src: traefik/routers.yml.j2
        dest: /opt/pods/traefik/providers/routers.yml
        mode: "0644"

    - name: Create service config
      ansible.builtin.template:
        src: traefik/services.yml.j2
        dest: /opt/pods/traefik/providers/services.yml
        mode: "0644"
