---
- name: Create docker containers
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: "{{ item.state | default('started') }}"
    restart_policy: "{{ item.restart | default(true) }}"
    network_mode: "{{ item.network | default('bridge') }}"
    ports:
      - "{{ item.ports | default([]) }}"
    user: "{{ item.user | default('root') }}"
    env: "{{ item.env | default([]) }}"
    devices: "{{ item.devices | default([]) }}"
    volumes: "{{ item.volumes | default([]) }}"
