---
- name: "Checking for volume: {{ item.name }}"
  register: volume
  failed_when: false
  community.docker.docker_volume_info:
    name: "{{ item.name }}"

- name: "Create volume: {{ item.name }}"
  when: volume.exists is false
  community.docker.docker_volume:
    name: "{{ item.name }}"
    driver: "{{ item.driver }}"
    state: present
