---
pods:
  - name: scrutiny-collector
    image: ghcr.io/analogj/scrutiny:v0.8.1-collector
    capabilities:
      - SYS_ADMIN
      - SYS_RAWIO
    env:
      COLLECTOR_API_ENDPOINT: "http://vpod:8934"
      COLLECTOR_HOST_ID: "{{ inventory_hostname }}"
      COLLECTOR_CRON_SCHEDULE: "0 * * * *"
      COLLECTOR_RUN_STARTUP: "true"
    volumes: ["/run/udev:/run/udev:ro"]
    devices: ["/dev/nvme0"]
    state: absent

  - name: garage
    image: docker.io/dxflrs/garage:v2.1.0
    network_mode: host
    volumes:
      - "/opt/pods/garage/config/garage.toml:/etc/garage.toml"
      - "/opt/pods/garage/meta:/var/lib/garage/meta"
      - "/opt/pods/garage/data:/var/lib/garage/data"

pod_volumes:
  - name: model-cache
    driver: local

pod_networks:
  - name: proxy
    driver: local
  - name: scrutiny
    driver: local
  - name: media
    driver: local
  - name: monitor
    driver: local
  - name: immich
    driver: local
