---
- name: Run host setup tasks
  hosts: linux
  become: true
  tasks:
    - name: Update hosts
      ansible.builtin.include_role:
        name: update_hosts
        apply:
          tags: update
      tags:
        - update

    - name: Get service facts
      ansible.builtin.service_facts:
      tags:
        - service_facts

    - name: Run standard setup tasks
      when: ansible_os_family == 'Debian'
      ansible.builtin.include_role:
        name: deb_setup
        apply:
          tags:
            - setup
            - all
      tags:
        - setup
        - all

    - name: Install node exporter
      when:
        - req_monitor | default(false)
        - ansible_facts.services['node_exporter.service'] is not defined
      ansible.builtin.include_role:
        name: prometheus.prometheus.node_exporter
        apply:
          tags:
            - prometheus
            - all
      tags:
        - prometheus
        - all

    - name: Setup NUT client
      when: req_nut | default(false)
      tags:
        - nut
        - all
      block:
        - name: Lookup NUT secret
          ansible.builtin.set_fact:
            nut_client_password: "{{ lookup('ripplefcl.bwscache.secret', 'nut-password').value }}"
          no_log: true

        - name: Install NUT client
          ansible.builtin.include_role:
            name: geerlingguy.nut_client
            apply:
              tags:
                - nut
                - all
              no_log: true

    - name: Install docker
      when:
        - req_docker | default(false)
        - ansible_facts.services['docker.service'] is not defined
      ansible.builtin.include_role:
        name: geerlingguy.docker
        apply:
          tags:
            - docker
            - all
      tags:
        - docker
        - all

    - name: Install libvirt
      when:
        - req_virt | default(false)
        - ansible_os_family == 'Debian'
        - ansible_facts.services['libvirtd.service'] is not defined
      ansible.builtin.include_role:
        name: deb_virt
        apply:
          tags:
            - virt
            - all
      tags:
        - virt
        - all
