---
- name: Run host setup tasks
  hosts: linux
  become: true
  tasks:
    - name: Update hosts
      ansible.builtin.include_role:
        name: update_hosts
        apply:
          tags: update
      tags:
        - update

    - name: Get service facts
      ansible.builtin.service_facts:
      tags:
        - service_facts

    - name: Print service facts
      ansible.builtin.debug:
        var: ansible_facts.services
      tags:
        - service_facts

    # - name: Gather facts about libvirt network
    #   community.libvirt.virt_net:
    #     command: facts
    #   tags:
    #     - virt_facts

    # - name: Print virt network facts
    #   ansible.builtin.debug:
    #     var: ansible_facts.libvirt_networks
    #   tags:
    #     - virt_facts

    - name: Run standard setup tasks
      when: ansible_os_family == 'Debian'
      ansible.builtin.include_role:
        name: deb_setup
        apply:
          tags: setup
      tags:
        - setup

    - name: Install node exporter
      when: req_monitor | default(false)
      ansible.builtin.include_role:
        name: prometheus.prometheus.node_exporter
        apply:
          tags:
            - prometheus
      tags:
        - prometheus

    - name: Install NUT client
      when: req_nut | default(false)
      ansible.builtin.include_role:
        name: geerlingguy.nut_client
        apply:
          tags:
            - nut
      tags:
        - nut

    - name: Install docker
      when: req_docker | default(false)
      ansible.builtin.include_role:
        name: geerlingguy.docker
        apply:
          tags: docker
      tags:
        - docker

    - name: Install libvirt
      when: req_virt | default(false)
      ansible.builtin.include_role:
        name: deb_virt
        apply:
          tags:
            - virt
      tags:
        - virt
