---
- name: Run host setup tasks
  hosts: linux
  become: true
  tasks:
    - name: Update hosts
      ansible.builtin.include_role:
        name: update_hosts
        apply:
          tags: update
      tags:
        - update

    - name: Run standard setup tasks
      when: ansible_os_family == 'Debian'
      ansible.builtin.include_role:
        name: deb_setup
        apply:
          tags: setup
      tags:
        - setup

    - name: Install node exporter
      when: req_monitor | default(false)
      ansible.builtin.include_role:
        name: prometheus.prometheus.node_exporter
        apply:
          tags:
            - prometheus
      tags:
        - prometheus

    - name: Install NUT client
      when: req_nut | default(false)
      ansible.builtin.include_role:
        name: geerlingguy.nut_client
        apply:
          tags:
            - nut
      tags:
        - nut

    - name: Install docker
      when: req_docker | default(false)
      ansible.builtin.include_role:
        name: geerlingguy.docker
        apply:
          tags: docker
      tags:
        - docker

    - name: Install libvirt
      when: req_virt | default(false)
      ansible.builtin.include_role:
        name: deb_virt
        apply:
          tags:
            - virt
      tags:
        - virt
