---
- name: Run host setup tasks
  hosts: debian
  become: true
  tasks:
    - name: Run standard setup tasks
      ansible.builtin.include_role:
        name: deb_setup
      when: ansible_os_family == 'Debian'

    - name: Install node exporter
      ansible.builtin.include_role:
        name: prometheus.prometheus.node_exporter

    - name: Install NUT client
      ansible.builtin.include_role:
        name: geerlingguy.nut_client
      when: req_nut

    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
      when: req_docker
