---
- name: Update Linux hosts
  hosts: linux
  become: true
  tasks:
    - name: Update RHEL Hosts
      when: ansible_os_family == 'RedHat'
      block:
        - name: Upgrade all DNF packages
          ansible.builtin.dnf:
            state: latest
            name: '*' # noqa package-latest

        - name: DNF autoremove packages
          ansible.builtin.dnf:
            autoremove: true

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /run/reboot-required
      register: reboot_required

    - name: Reboot if required
      ansible.builtin.reboot:
      when: reboot_required.stat.exists
