---
- name: Update Linux hosts
  hosts: linux
  become: true
  tasks:
    - name: Update RHEL Hosts
      when: ansible_os_family == 'RedHat'
      block:
        - name: Upgrade all DNF packages
          ansible.builtin.dnf:
            state: latest
            name: '*' # noqa package-latest

        - name: DNF autoremove packages
          ansible.builtin.dnf:
            autoremove: true

        - name: Check if reboot is required
          ansible.builtin.command: needs-restarting -r
          register: reboot_required
          failed_when: false
          changed_when: reboot_required.rc == 1
          notify: Reboot if required

    - name: Update Debian-based hosts
      when: ansible_os_family == 'Debian'
      block:
        - name: Update Debian
          ansible.builtin.apt:
            update_cache: true
            upgrade: full
            autoremove: true
            autoclean: true

        - name: Check if reboot is required
          ansible.builtin.stat:
            path: /var/run/reboot-required
          register: reboot_required
          notify: Reboot if required

  handlers:
    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Machine rebooting for updates"
        reboot_timeout: 300
