---
- name: Update Debian-based hosts
  hosts: debian,ubuntu
  become: true
  tasks:
    - name: Update Debian
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
        autoremove: true
        autoclean: true
