---
- name: "Create container config directory"
  become: true
  ansible.builtin.file:
    path: "{{ monitor_pods_path }}/{{ pod.name }}/config"
    state: directory
    recurse: true
    mode: '0740'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop: "{{ monitor_pods_def }}"
  loop_control:
    label: "{{ pod.name }}"
    loop_var: pod

- name: "Create container data directory"
  become: true
  ansible.builtin.file:
    path: "{{ monitor_pods_path }}/{{ pod.name }}/data"
    state: directory
    recurse: true
    mode: '0740'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop: "{{ monitor_pods_def }}"
  loop_control:
    label: "{{ pod.name }}"
    loop_var: pod

- name: Set template for mktxp.conf
  become: true
  ansible.builtin.template:
    src: mktxp/mktxp.conf.j2
    dest: "{{ monitor_pods_path }}/mktxp/config/mktxp.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0740'

- name: Copy _mktxp.conf file
  become: true
  ansible.builtin.copy:
    src: mktxp/_mktxp.conf
    dest: "{{ monitor_pods_path }}/mktxp/config/_mktxp.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0740'

- name: Create prometheus.yml based on template
  become: true
  ansible.builtin.template:
    src: prometheus/prometheus.yml.j2
    dest: "{{ monitor_pods_path }}/prometheus/config/prometheus.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0740'
  notify: Restart prometheus

- name: "Create container"
  community.docker.docker_container:
    name: "{{ pod.name }}"
    image: "{{ pod.image }}"
    state: "{{ pod.state | default('started') }}"
    restart_policy: "{{ pod.restart | default('unless-stopped') }}"
    networks: "{{ pod.networks | default(omit) }}"
    network_mode: "{{ pod.network_mode | default(omit) }}"
    capabilities: "{{ pod.capabilities | default(omit) }}"
    security_opts: "{{ pod.security_opt | default(omit) }}"
    ports: "{{ pod.ports | default(omit) }}"
    user: "{{ pod.user | default(omit) }}"
    env: "{{ pod.env | default(omit) }}"
    devices: "{{ pod.devices | default(omit) }}"
    volumes: "{{ pod.volumes | default(omit) }}"
    log_driver: "{{ pod.log_driver | default(omit) }}"
    log_options: "{{ pod.log_options | default(omit) }}"
    default_host_ip: "{{ default_host_ip }}"
  loop: "{{ monitor_pods_def }}"
  loop_control:
    label: "{{ pod.name }}"
    loop_var: pod
