---
- name: Set template for prometheus.yml
  ansible.builtin.template:
    src: prometheus/prometheus.yml
    dest: "{{ monitor_pods_path }}/{{ item.name }}/config/prometheus.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0640'
