---
default_host_ip: ""

pods:
  - name: nut
    image: ghcr.io/tigattack/nut-upsd:2.8.2
    restart: unless-stopped
    state: started
    networks:
      - name: nut
    ports:
      3493:3493
    env:
      NUT_UID: "{{ ansible_facts.user_uid }}"
      NUT_GID: "{{ ansible_facts.user_gid }}"
    devices:
      /dev/bus/usb/001/004:/dev/bus/usb/001/004
    volumes:
      ~/pods/nut/data:/etc/nut:ro
    directory: true

  - name: nut-exporter
    image: ghcr.io/druggeri/nut_exporter:3.2.0
    restart: unless-stopped
    state: started
    networks:
      - name: nut
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    ports:
      9199:9199
    env:
      NUT_EXPORTER_USERNAME: observer
      NUT_EXPORTER_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'nut').value }}"
      NUT_EXPORTER_SERVER: nut
      NUT_EXPORTER_PORT: "3493"
      NUT_EXPORTER_VARIABLES: >-
          battery.charge,battery.charge.low,battery.runtime,battery.runtime.low,
          battery.voltage,battery.voltage.nominal,input.voltage,input.voltage.nominal,
          outlet.power,output.power,output.voltage,ups.load,ups.realpower.nominal,ups.status

  - name: nginx-uptime
    image: public.ecr.aws/nginx/nginx:1.28.0
    restart: unless-stopped
    state: started
    directory: true
    volumes:
      - "~/pods/nginx-uptime/www:/var/www"
      - "~/pods/nginx-uptime/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      8083:80
    env:
      NGINX_HOST: "{{ lookup('ripplefcl.bwscache.secret', 'domain_lab').value }}"
      NGINX_PORT: "80"

  - name: nginx-files
    image: public.ecr.aws/nginx/nginx:1.28.0
    restart: unless-stopped
    state: started
    directory: true
    volumes:
      - "~/pods/nginx-files/www:/var/www"
      - "~/pods/nginx-files/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      8084:80
    env:
      NGINX_HOST: "{{ lookup('ripplefcl.bwscache.secret', 'domain_files').value }}"
      NGINX_PORT: "80"

pod_networks:
  - name: nut
    driver: local
