---
- name: Install standard packages
  ansible.builtin.apt:
    name:
      - git
      - vim
      - nano
      - tmux
      - htop
      - fzf
      - smartmontools
      - net-tools
      - tcpdump
      - bind9-utils
      - nfs-common
      - cifs-utils
      - lm-sensors
      - tree
      - rsync
      - jq
      - bind9-dnsutils
      - curl
      - wget
      - openvswitch-switch-dpdk
      - netplan.io
      - systemd-resolved
      - python3-requests
      - tuned
    state: present
