---
- name: Install standard packages
  ansible.builtin.apt:
    name:
      - git
      - vim
      - tmux
      - htop
      - nfs-common
      - lm-sensors
      - tree
      - jq
      - curl
      - systemd-resolved
      - python3-requests
    state: present
