---
- name: "Create networks"
  register: result
  failed_when: false
  community.docker.docker_network:
    name: "{{ net.name }}"
    state: present
  loop: "{{ pod_networks }}"
  loop_control:
    label: "{{ net.name }}"
    loop_var: net
