---
- name: "Create directories"
  when: pod.directory is defined
  become: true
  changed_when: false
  ansible.builtin.file:
    path: "/opt/pods/{{ pod.name }}"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop: "{{ pods }}"
  loop_control:
    label: "{{ pod.name }}"
    loop_var: pod

- name: "Create docker containers" # noqa args[module]
  community.docker.docker_container: "{{ pod | default([]) }}"
  loop: "{{ pods }}"
  loop_control:
    label: "{{ pod.name }}"
    loop_var: pod
