---
- name: Refresh DNF cache
  ansible.builtin.dnf:
    update_cache: true

- name: Enable CRB Repo
  ansible.builtin.dnf:
    enablerepo: crb

- name: Install epel-release
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Install standard packages
  ansible.builtin.dnf:
    name:
      - nano
      - vim
      - htop
      - tmux
      - PackageKit-command-not-found
      - zsh
      - thefuck
      - autojump
      - tmux
      - rsync
      - git
      - nfs-utils
      - nload
      - net-tools
      - tcpdump
      - cockpit
      - cockpit-pcp
      - bind-utils
      - cifs-utils
      - nfs-utils
      - rpmfusion-free-release
      - rpmfusion-free-release-tainted
      - systemd-resolved
      - firewalld
      - python-firewall
    state: present

- name: Setup systemd-resolved
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    owner: 193
    group: 193
    state: link
    force: true

- name: Enable systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    enabled: true
    state: started

- name: Start Cockpit & related services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - cockpit.socket
    - pmlogger.service

- name: Create smithy group
  ansible.builtin.group:
    name: smithy
    gid: 10337
    state: present

- name: Add user to Smithy group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: smithy
    append: true
  notify:
    - Refresh SSH
