---
- name: Install standard packages
  ansible.builtin.apt:
    name:
      - binfmt-support
      - libguestfs-tools
      - libqcow-utils
      - libvirt-clients
      - libvirt-daemon
      - libvirt-daemon-driver-qemu
      - libvirt-daemon-system
      - libvirt-daemon-system-systemd
      - ovmf
      - prometheus-libvirt-exporter
      - qemu-block-extra
      - qemu-efi
      - qemu-system
      - qemu-system-x86
      - qemu-user
      - qemu-user-binfmt
      - qemu-utils
      - virtinst
      - virtnbdbackup
    install_recommends: false
    state: present
