---
- name: Gather facts about libvirt network
  community.libvirt.virt_net:
    command: facts

- name: Install apt packages
  ansible.builtin.include_tasks: install.yml

- name: Configure libvirt
  ansible.builtin.include_tasks: config.yml

- name: Start libvirt services
  ansible.builtin.include_tasks: services.yml
