---
- name: Start libvirt services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - libvirtd.socket
    - libvirtd-ro.socket
    - libvirtd-admin.socket
    - libvirtd.service
    - libvirt-guests.service
    - prometheus-libvirt-exporter.service

- name: Disable dnsmasq service
  when: ansible_facts.services['dnsmasq.service'] is defined
  ansible.builtin.systemd:
    name: dnsmasq.service
    enabled: false
    state: stopped
  notify: restart dnsmasq
