---
- name: Create /opt/virt directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    recurse: true
    mode: '0775'
    owner: libvirt-qemu
    group: kvm
  failed_when: false
  changed_when: false

- name: Create storage pool
  community.libvirt.virt_pool:
    name: "{{ item.name }}"
    command: define
    xml: "{{ lookup('template', 'libvirt-pool.xml.j2') }}"

- name: Start storage pools
  community.libvirt.virt_pool:
    name: "{{ item.name }}"
    state: active

- name: Autostart storage pools
  community.libvirt.virt_pool:
    name: "{{ item.name }}"
    autostart: true
