---
- name: Install packages
  ansible.builtin.dnf:
    name:
      - qemu-kvm
      - qemu-img
      - edk2-ovmf
      - libvirt
      - virt-install
      - bridge-utils
      - virt-top
      - libguestfs-tools
      - cockpit-machines
    state: present

- name: Enable & Start 'libvirtd' service
  ansible.builtin.systemd_service:
    name: libvirtd
    state: started
    enabled: true

- name: Copy libvirt-guests config to sysconfig
  ansible.builtin.copy:
    content: "{{ setup_virt_libvirt_guests }}"
    dest: /etc/sysconfig/libvirt-guests
    owner: root
    group: root
    mode: '0644'

- name: Enable & Start 'libvirt-guests' service
  ansible.builtin.systemd_service:
    name: libvirt-guests
    state: started
    enabled: true

- name: Add groups
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups: libvirt,kvm
  notify:
    - Refresh SSH
