---
standard_pod_path_prefix: "/opt/pods"

pods:
  - name: traefik
    image: public.ecr.aws/docker/library/traefik:v3.5.2
    network_mode: host
    env:
      BUNNY_API_KEY: "{{ lookup('ripplefcl.bwscache.secret', 'bunny_api').value }}"
      BUNNY_POLLING_TIMEOUT: "600"
      BUNNY_POLLING_INTERVAL: "5"
      BUNNY_TTL: "3600"
      CF_API_EMAIL: "{{ lookup('ripplefcl.bwscache.secret', 'will_email').value }}"
      CF_API_KEY: "{{ lookup('ripplefcl.bwscache.secret', 'cf_token').value }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/opt/pods/traefik/config/traefik.yml:/traefik.yml:ro"
      - "/opt/pods/traefik/config/providers:/providers:ro"
      - "/opt/pods/traefik/config/acme.json:/acme.json"

  - name: immich-public-proxy
    image: ghcr.io/alangrainger/immich-public-proxy:1.13.1
    network_mode: host
    env:
      IMMICH_URL: "http://[fd72:1432:d17a:0:be24:11ff:fe8a:aa24]:2283"

  - name: meshmon
    image: ghcr.io/ripplefcl/meshmon:v2.0.4
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    network_mode: host
    volumes: ["{{ standard_pod_path_prefix }}/meshmon/config:/app/config"]
