---
# libvirt-main
deb_libvirt_default_uri: qemu:///system
deb_libvirt_bridge_helper: /usr/lib/qemu/qemu-bridge-helper
deb_libvirt_gid: kvm

# libvirt-guests
deb_libvirt_guests_boot: start
deb_libvirt_guests_startup_delay: 20
deb_libvirt_guests_shutdown_action: shutdown
deb_libvirt_guests_shutdown_parallel: 0
deb_libvirt_guests_shutdown_delay: 300
deb_libvirt_guests_bypass_cache: 0
deb_libvirt_guests_sync_time: 0

# libvirt-network
deb_libvirt_net_nics:
  - name: lan
    nic: vmbr0
  - name: opnlan
    nic: vmbr50
  - name: opngst
    nic: vmbr240
  - name: opnwan
    nic: vmbr998

# libvirt-storage
deb_libvirt_storage_pools:
  - name: images
    path: /opt/virt/images
  - name: iso
    path: /opt/shares/virt/iso
  - name: templates
    path: /opt/shares/virt/templates
