---
- name: Setup Media box
  hosts: smi-rl-02
  become: true
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
    - host_setup
  tasks:
    - name: Install elrepo-release
      ansible.builtin.dnf:
        name: elrepo-release
        state: present

    - name: Allow loading of GuC & HuC hardware for low-power encode
      ansible.builtin.copy:
        dest: /etc/modprobe.d/i915.conf
        content: 'options i915 enable_guc=2'
        mode: '0755'
        owner: root

    - name: Mainline Kernel install
      when: ansible_facts['kernel'] is not search('elrepo')
      block:
        - name: Install mainline kernel
          ansible.builtin.dnf:
            enablerepo: elrepo-kernel
            name:
              - kernel-ml
              - kernel-ml-devel
            state: present

        - name: Regen initramfs
          ansible.builtin.command: dracut -fp --regenerate-all
          register: 'r_dracut'
          changed_when: r_dracut is succeeded

        - name: Regen GRUB config
          ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
          register: 'r_grubcfg'
          changed_when: r_grubcfg is succeeded

        - name: Reboot System
          ansible.builtin.reboot:
