---
- name: Setup Media box
  hosts: smi-rl-03
  become: true
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
    - host_setup
  tasks:
    # - name: Install elrepo-release
      # ansible.builtin.dnf:
        # name: elrepo-release
        # state: present

    - name: Allow loading of GuC & HuC hardware for low-power encode
      ansible.builtin.copy:
        dest: /etc/modprobe.d/i915.conf
        content: 'options i915 enable_guc=2'
        mode: '0755'
        owner: root
      register: r_i915
      notify: Regen initramfs

    - name: Add groups
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        append: true
        groups: render,video,audio
      notify:
        - Refresh SSH

  handlers:
    - name: Refresh SSH
      ansible.builtin.meta: reset_connection

    - name: Regen initramfs
      ansible.builtin.command: dracut -fp --regenerate-all
      register: 'r_dracut'
      changed_when: r_dracut is succeeded
      when: r_i915.changed
      notify: Reboot System

    - name: Reboot System
      ansible.builtin.reboot:
