---
- name: Run host setup play
  hosts: rhel
  become: true
  roles:
    - role: setup_host
    - role: prometheus.prometheus.node_exporter
  tasks:
    - name: Load sops variables
      community.sops.load_vars:
        file: tail.sops.yaml

    - name: Set IPv4 forward
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: true
        state: present
        reload: true

    - name: Set IPv6 forward
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: 1
        sysctl_set: true
        state: present
        reload: true

    - name: Allow masq
      ansible.posix.firewalld:
        masquerade: true
        state: enabled
        permanent: true
