---
- name: Gather & print facts
  hosts: switches
  gather_facts: false
  tasks:
    - name: Collect default set of facts
      junipernetworks.junos.junos_facts:

    - name: Remove virtual chassis ports
      junipernetworks.junos.junos_command:
        commands:
          - request virtual-chassis vc-port delete pic-slot 1 port 0
          - request virtual-chassis vc-port delete pic-slot 1 port 1
          - request virtual-chassis vc-port delete pic-slot 1 port 2
          - request virtual-chassis vc-port delete pic-slot 1 port 3
      when: "'ex4300' in ansible_net_model"

    - name: Set hostname and DNS
      junipernetworks.junos.junos_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: mgt.lan
        domain_search:
          - mgt.lan
        name_servers:
          - 172.16.16.2
        state: absent

    - name: Set ntp servers
      junipernetworks.junos.junos_ntp_global:
        config:
          servers:
            - server: 216.239.35.0
              prefer: true
            - server: 216.239.35.4
        state: replaced

    - name: Enable snmp
      junipernetworks.junos.junos_snmp_server:
        config:
          communities:
            - name: public
              authorization: read-only
        state: replaced

    - name: Enable lldp
      junipernetworks.junos.junos_lldp_global:
        config:
          address: "{{ ansible_host }}"
          enabled: true
        state: replaced

    - name: Configure VLANs
      junipernetworks.junos.junos_vlans:
        config:
          - name: mgt
            vlan_id: 97
            l3_interface: irb.97
          - name: home
            vlan_id: 98
            l3_interface: irb.98
          - name: transit
            vlan_id: 172
            l3_interface: irb.172
          - name: will-work
            vlan_id: 990
            l3_interface: irb.990
          - name: john-work
            vlan_id: 991
            l3_interface: irb.991
          - name: WAN
            vlan_id: 998
          - name: WAN2
            vlan_id: 999
        state: replaced

    - name: Configure L2 interfaces
      junipernetworks.junos.junos_l2_interfaces:
        config:
          - name: ge-0/0/0
            trunk:
              allowed_vlans:
                - mgt
                - home
                - transit
                - will-work
                - john-work
                - WAN
                - WAN2
            unit: 0
        state: replaced

    - name: Configure IRBs
      junipernetworks.junos.junos_l3_interfaces:
        config:
          - name: irb
            unit: 98
            ipv4:
              - address: 10.141.98.1/24
          - name: irb
            unit: 172
            ipv4:
              - address: 172.16.16.1/30
          - name: irb
            unit: 990
            ipv4:
              - address: 10.141.99.1/29
          - name: irb
            unit: 991
            ipv4:
              - address: 10.141.99.9/29
        state: replaced

    # - name: "Delete given options for the interface (Note: This won't delete the interface itself if any other values are configured for interface)"
    #   junipernetworks.junos.junos_interfaces:
    #     config:
    #       - name: ge-0/0/1
    #         description: Configured by Ansible-1
    #         speed: 1g
    #         mtu: 1800
    #       - name: ge-0/0/2
    #         description: Configured by Ansible -2
    #     state: deleted

    - name: Update rescue config
      junipernetworks.junos.junos_command:
        commands:
          - request system configuration rescue save
