---
- name: Gather & print facts
  hosts: switches
  gather_facts: false
  tasks:
    - name: Gather legacy and resource facts
      junipernetworks.junos.junos_facts:
        # gather_subset: all
        # gather_network_resources: all

    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
