---
- name: Refresh SSH
  ansible.builtin.meta: reset_connection

- name: Regen initramfs
  ansible.builtin.command: dracut -fp --regenerate-all
  register: 'r_dracut'
  changed_when: r_dracut is succeeded
  notify: Reboot System

- name: Reboot System
  ansible.builtin.reboot:
