---
seaweedfs_image: docker.io/chrislusf/seaweedfs:3.98_large_disk
seaweedfs_replication: "002"
seaweedfs_max_volumes: 100

seaweedfs_peers: >-
  {{
    groups['seaweedfs']
    | map('extract', hostvars, ['ansible_default_ipv4', 'address'])
    | join(',')
  }}

seaweedfs_filer_config: |
  [postgres2]
  enabled = true
  hostname = "vdb1"
  port = 15004
  username = "seaweed"
  password = "{{ lookup('ripplefcl.bwscache.secret', 'seaweed_db_pass').value }}"
  database = "seaweed"
  schema = "public"
  sslmode = "disable"
  connection_max_idle = 10
  connection_max_open = 100
  connection_max_lifetime_seconds = 0
  enableUpsert = true
  createTable = """
  CREATE TABLE IF NOT EXISTS "%s" (
    dirhash BIGINT,
    name VARCHAR(65535),
    directory VARCHAR(65535),
    meta bytea,
    PRIMARY KEY (dirhash, name)
  )
  """
