---
- name: Upgrade using dnf
  ansible.builtin.dnf:
    state: latest
    name: '*' # noqa package-latest

- name: DNF autoremove packages
  ansible.builtin.dnf:
    autoremove: true

- name: Check if reboot is required
  ansible.builtin.command: needs-restarting -r
  register: reboot_required
  failed_when: false
  changed_when: reboot_required.rc == 1
  notify: Reboot if required
