---
- name: PVE Repo Setup
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    filename: pve-sources
  loop:
    - "deb http://download.proxmox.com/debian/ceph-quincy {{ ansible_distribution_release }} no-subscription"
    - "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
