---
- name: Remove subscription prompt
  ansible.builtin.include_tasks:
    file: remove-prompt.yml
  when: pve_setup_remove_prompt

- name: Remove old repo file
  ansible.builtin.include_tasks:
    file: remove-repos.yml
  when: pve_setup_remove_repos

- name: Add PVE Repo
  ansible.builtin.include_tasks:
    file: add-repos.yml
  when: pve_setup_add_repos
