---
- name: Remove old repo file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-sources.list
    state: absent

- name: Remove repos
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: absent
    update_cache: false
  loop:
    - "deb http://download.proxmox.com/debian/ceph-quincy {{ ansible_distribution_release }} enterprise"
    - "deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise"
