---
default_host_ip: ""

standard_pod_path_prefix: "/opt/pods"
storage_pod_path_prefix: "/opt/pods"

pods:
  - name: scrutiny-collector
    image: ghcr.io/analogj/scrutiny:v0.8.1-collector
    restart: unless-stopped
    state: started
    capabilities:
      - SYS_ADMIN
      - SYS_RAWIO
    env:
      COLLECTOR_API_ENDPOINT: "{{ lookup('ripplefcl.bwscache.secret', 'scrutiny_domain').value }}"
      COLLECTOR_HOST_ID: "{{ inventory_hostname }}"
      COLLECTOR_CRON_SCHEDULE: "0 * * * *"
      COLLECTOR_RUN_STARTUP: "true"
    volumes:
      - "/run/udev:/run/udev:ro"
    devices:
      - /dev/nvme0
      - /dev/nvme1
