---
- name: Install standard packages
  ansible.builtin.apt:
    name: "{{ standard_packages + (additional_packages | default([])) }}"
    state: present
  vars:
    standard_packages:
      - git
      - vim
      - tmux
      - htop
      - nfs-common
      - lm-sensors
      - tree
      - jq
      - curl
      - systemd-resolved
      - python3-requests
