---
monitor_pods_path: /opt/pods/monitor

monitor_pods_def:
  - name: prometheus
    image: quay.io/prometheus/prometheus:v3.4.2
    container_name: prometheus
    restart: unless-stopped
    state: started
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    default_host_ip: ""
    networks:
      - name: proxy
      - name: monitor
    volumes:
      - "{{ monitor_pods_path }}/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "{{ monitor_pods_path }}/prometheus/data:/prometheus"

  - name: mktxp
    image: ghcr.io/akpw/mktxp:1.2.10
    container_name: mktxp
    restart: unless-stopped
    state: started
    user: root
    default_host_ip: ""
    networks:
      - name: monitor
    volumes:
      - "{{ monitor_pods_path }}/mktxp/config:/root/mktxp"

  - name: mysqld_exporter
    image: docker.io/prom/mysqld-exporter:v0.17.2
    container_name: mysqld_exporter
    restart: unless-stopped
    state: started
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    default_host_ip: ""
    networks:
      - name: monitor
    ports:
      - 9104:9104
    env:
      MYSQLD_EXPORTER_PASSWORD: "{{ lookup('ripplefcl.bwscache.secret', 'dad_db_root').value }}"
    volumes:
      - "{{ monitor_pods_path }}/mysqld_exporter/config/user_my.cnf:/.my.cnf"

  - name: grafana
    image: docker.io/grafana/grafana:12.0.2
    container_name: grafana
    restart: unless-stopped
    state: started
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    default_host_ip: ""
    networks:
      - name: proxy
      - name: monitor
    env:
      GF_INSTALL_PLUGINS: grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel
    volumes:
      - "{{ monitor_pods_path }}/grafana/data:/var/lib/grafana"

  - name: loki
    image: grafana/loki:3.5.1
    container_name: loki
    restart: unless-stopped
    state: started
    user: "{{ ansible_facts.user_uid }}"
    default_host_ip: ""
    networks:
      - name: monitor
    volumes:
      - "{{ monitor_pods_path }}/loki/config:/mnt/config"
      - "{{ monitor_pods_path }}/loki/data:/loki"

  - name: promtail
    image: grafana/promtail:3.5.1
    container_name: promtail
    restart: unless-stopped
    state: started
    default_host_ip: ""
    networks:
      - name: monitor
    volumes:
      - "{{ monitor_pods_path }}/promtail/config:/mnt/config"
      - "/var/log:/var/log"

monitor_prometheus_config:
  - job_name: "node-exporter"
    scheme: http
    static_configs:
      - targets:
          - 'sbc2:9100'
          - 'sbc4:9100'
          - 'nas1:9100'
          - 'kvm1:9100'
          - 'dl1:9100'
          - 'vws1:9100'
          - 'vwkr1:9100'
          - 'vwkr2:9100'
          - 'vwkr3:9100'
          - 'vgm1:9100'
          - 'vdb1:9100'
          - 'homeassistant:9100'
          - "{{ lookup('ripplefcl.bwscache.secret', 'vps1_domain').value }}:9100"

  - job_name: "gravity"
    static_configs:
      - targets:
          - 10.10.0.3:8009

  - job_name: "unpoller"
    scheme: http
    static_configs:
      - targets: ["sbc4:9130"]

  - job_name: "mktxp"
    static_configs:
      - targets: ["mktxp:49090"]

  - job_name: mysql
    metrics_path: /probe
    static_configs:
      - targets: ["10.10.0.185:15000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mysqld_exporter:9104

  - job_name: incus
    metrics_path: '/1.0/metrics'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['kvm1:8443']
