---
monitor_pods_path: /opt/pods/monitor

monitor_pods_def:
  - name: prometheus
    image: quay.io/prometheus/prometheus:v3.4.1
    container_name: prometheus
    restart: unless-stopped
    state: started
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    default_host_ip: ""
    networks:
      - name: proxy
      - name: monitor
    volumes:
      - "{{ monitor_pods_path }}/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "{{ monitor_pods_path }}/prometheus/data:/prometheus"

  - name: mktxp
    image: ghcr.io/akpw/mktxp:1.2.10
    container_name: mktxp
    restart: unless-stopped
    state: started
    user: root
    default_host_ip: ""
    networks:
      - name: monitor
    volumes:
      - "{{ monitor_pods_path }}/mktxp/config:/root/mktxp"

  - name: grafana
    image: docker.io/grafana/grafana:12.0.1
    container_name: grafana
    restart: unless-stopped
    state: started
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    default_host_ip: ""
    networks:
      - name: proxy
      - name: monitor
    env:
      GF_INSTALL_PLUGINS: grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel
    volumes:
      - "{{ monitor_pods_path }}/grafana/data:/var/lib/grafana"

monitor_prometheus_config:
  - job_name: "node-exporter"
    scheme: http
    static_configs:
      - targets:
          - 'sbc1:9100'
          - 'sbc2:9100'
          - 'sbc3:9100'
          - 'sbc4:9100'
          - 'nas1:9100'
          - 'kvm1:9100'
          - 'dl1:9100'
          - "{{ lookup('ripplefcl.bwscache.secret', 'domain_vps1').value }}:9100"

  - job_name: "gravity"
    static_configs:
      - targets:
          - 10.10.0.3:8009

  - job_name: "nut-exporter"
    metrics_path: "/ups_metrics"
    scheme: http
    static_configs:
      - targets: ["sbc1:9199"]
        labels:
          ups: "primary"
    params:
      ups: ["will-office-eaton"]

  - job_name: "unpoller"
    scheme: http
    static_configs:
      - targets: ["sbc3:9130"]

  - job_name: "mktxp"
    static_configs:
      - targets: ["mktxp:49090"]
