---
monitor_pods_path: /opt/pods/monitor

monitor_pods:
  - name: prometheus
    image: quay.io/prometheus/prometheus:v3.4.0
    container_name: prometheus
    restart: unless-stopped
    state: started
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    default_host_ip: ""
    networks:
      - name: proxy
      - name: monitor
    volumes:
      - "{{ monitor_pods_path }}/{{ item.name }}/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "{{ monitor_pods_path }}/{{ item.name }}/data:/prometheus"

  - name: mktxp
    image: ghcr.io/akpw/mktxp:1.2.10
    container_name: mktxp
    restart: unless-stopped
    state: started
    user: root
    default_host_ip: ""
    networks:
      - name: monitor
    volumes:
      - "{{ monitor_pods_path }}/{{ item.name }}/config:/root/mktxp"

  - name: grafana
    image: docker.io/grafana/grafana:12.0.1
    container_name: grafana
    restart: unless-stopped
    state: started
    user: "{{ ansible_facts.user_uid }}:{{ ansible_facts.user_gid }}"
    default_host_ip: ""
    networks:
      - name: proxy
      - name: monitor
    env:
      GF_INSTALL_PLUGINS: grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel
    volumes:
      - "{{ monitor_pods_path }}/{{ item.name }}/data:/var/lib/grafana"
