---
- name: Update Debian-based Hosts
  hosts: debian
  become: true
  tasks:
    - name: Update APT cache, upgrade hosts, clean up
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: full
        autoremove: true
        autoclean: true

- name: Update RHEL Hosts
  hosts: rhel
  become: true
  tasks:
    - name: Upgrade all DNF packages
      ansible.builtin.dnf:
        state: latest
        name: '*' # noqa package-latest

    - name: DNF autoremove packages
      ansible.builtin.dnf:
        autoremove: true

    - name: Cleanup DNF
      ansible.builtin.command:
        cmd: dnf clean all
      changed_when: true

- name: Restart Linux hosts if required
  hosts: linux
  become: true
  tasks:
    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      ansible.builtin.reboot:
      when: reboot_required.stat.exists

- name: Update PVE Hosts
  hosts: proxmox
  tasks:
    - name: Full-upgrade all APT packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: full
        autoremove: true
        autoclean: true
