---
name: Terraform Lint

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        name: Checkout source code

      # - uses: actions/cache@v4
      #   name: Cache plugin dir
      #   with:
      #     path: ~/.tflint.d/plugins
      #     key: ubuntu-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v5
        name: Setup TFLint
        with:
          tflint_version: v0.57.0

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact --recursive --chdir terraform
